import sys

content = (
    "export interface ContactInfo {\n"
    "  email: string\n"
    "  linkedin: string\n"
    "  website: string\n"
    "  phone: string\n"
    "}\n"
    "\n"
    "export interface ExperienceEntry {\n"
    "  id: string\n"
    "  role: string\n"
    "  company: string\n"
    "  period: string\n"
    "  bullets: string[]\n"
    "  searchText: string\n"
    "}\n"
    "\n"
    "export interface EducationEntry {\n"
    "  degree: string\n"
    "  institution: string\n"
    "  year: string\n"
    "  note?: string\n"
    "  details?: string[]\n"
    "}\n"
    "\n"
    "export interface ResumeData {\n"
    "  name: string\n"
    "  title: string\n"
    "  contact: ContactInfo\n"
    "  summary: { tagline: string; body: string; searchText: string }\n"
    "  competencies: {\n"
    "    leadership: string[]\n"
    "    technical: string[]\n"
    "    socialService: string[]\n"
    "    searchText: string\n"
    "  }\n"
    "  experience: ExperienceEntry[]\n"
    "  education: { entries: EducationEntry[]; searchText: string }\n"
    "  certifications: { items: string[]; searchText: string }\n"
    "  vision: {\n"
    "    sections: { title: string; body: string }[]\n"
    "    closing: { title: string; body: string }\n"
    "    searchText: string\n"
    "  }\n"
    "}\n"
)

with open(sys.argv[1], "w", encoding="utf-8") as f:
    f.write(content)
print("phase1 done")
